spring:
    datasource:
        url: jdbc:mysql://rm-2ze0u477c69t0af47to.mysql.rds.aliyuncs.com:3306/yinpai?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
        username: yinpai
        password: yinpai123
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
#        show-sql: true #打印执行的sql语句
    freemarker:
        suffix: .ftl
    mvc:
        static-path-pattern: /static/**
    servlet:
      multipart:
        enabled: true
        max-file-size: 50MB
        max-request-size: 50MB

oss:
    access:
        keyId: "LTAI4GDrZ8bV6ZYEjbRe9TmC"
        keySecret: "3h3YJ4kxQIbpyt7N5FQk7Y2LSffBXW"
    bucketName: "yinpai"
    endpoint:
        outer: "oss-cn-beijing.aliyuncs.com"
        inner: "oss-cn-beijing-internal.aliyuncs.com"

yinpai:
#    url: http://localhost:8080
    url: http://182.92.123.102:8080

wechat:
    opAppId: wxecbe276412fb3eb8
    opMchId: 1604725045
    opMchkey: bc56e221598fc34298c8af55f2cafff7
    opNotifyUrl: https://ypapi.phpisfuture.com/mall/pay/callbackWxAppPay

jsapi:
    appid: wx96095d1c2acffb94
    EncodingAESKey: Qo5WWXRd1tc6lxmT14lWdJGfUjKELmL0m8GRUSdZAEN
    AppSecret: 83888971018c3054bd1ad72f099edea8
    notifyUrl: https://ypapi.phpisfuture.com/mall/pay/callbackjsApipayApp

alipay:
    serverUrl: https://openapi.alipay.com/gateway.do
    appId: 2021002114648310
    charset: utf-8
    signType: RSA2
    notifyUrl: https://ypapi.phpisfuture.com/mall/pay/callbackAlipayApp
    timeoutExpress: 10m
    alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAteyvDsVg/S4XCHAVxJRh5Gdio6Ryb2ELqRQ0mwMv+h4Jt7dVNbfmMz9k3M6nIbsYYYZuDqoHBFFLqwdQlwUlcopsTswxKJ9OBMX3aqVABD7Gd4wDcHdWB7czyyTCjIF9/5WR5MpWGGeXHm8cqfqzeJeq5MRMt8lrTglZRXkQcK2XDskII/Fquo3F+JiBJyhiWIl8uR4U6j5kRbPfelWbwJEIUOyKXY/qmdcWxiw8xLa/ide3DwkWwtwXMrT2ZbfAj2DuE9iG5F2iSlHNhUXCVB2J2QE/Gbi7rC3RKlzKGbZ7CBTEQNDH1hJEgZIWlciRm9Vote3+rvE7Gyw6hvQ1pQIDAQAB
    appPrivateKey: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCcFl7cfc4kIr5ycvBucvjnGz9g5htiXCYTaPFg0o4EJjH6Ia0597rf8tpH0BNzZEa+k8DPfLmpDeM/Lg3cSaOFrrKbFllZhPz643K9F6eM4P7yxAR+Jae4V0qNAQHGBksW320UiNnPOQiWXYkaNmJerrQekJlZttAXtRI0RF1PD9fs6uKZfbLyTkznUxjKVUVqPS8LvpMjTKK83O/DZn/5/CX2eJEczTBNFPFG3bQAsMXjvjwUMcjUzXTMUZvHLncq4TDGSAc35aFieVbpoF/KY8GnFJSH0S9UERppzjxzXcXKKn7M3JWpPPsdK6NHpHd6Ohl2W8W55AIn0tCwV0+vAgMBAAECggEAHnsH30r5/HiEdFkZtpfhH1Bk2glVg6m3DcdKi7vSW+ERlWUKLO3BooYMNkXd5oTIg+LaniofH3JE1EusDT6cHjj1S+/bVu3vcRcFiwOZhptRbhr1PaUg0ZDKUCrIK+GCvF65MG9hCWR71tFBOssv/oljRyy5pZlbnaWQfoBzMEL7St/9mWoCQFKOSsf82Fv5zFw8AJFeQvHNmjwWQZaMyQZV3Mxbv5uXlWSkyJX3gcTO2lf4qryinVCVLlVyA9TBpVwBqZDQcpD1aXNYg71Sb/q/EIbZl09xl5MnjRvSRpvPA7q2s6/IKR9zrs/VIS1wke+RtEw/frf4xGcEj8hPwQKBgQDd0B3bmC7y2yp3Au+kmfOzUBpQ2z67bnBRt4/BJHvVmmX0dkYhgUW7BSpEkY2DSTfWClaUOzUHGN2Dd7BdZpkh01UIelujbNwoBzRsMybqaQgw5kJxMCN04lLUK52DkgB6zxnruott/xz11u9eWpTaY2aYLNyZ5sROppgy+Oou8QKBgQC0JPn8IqQCp3dlcqUmz1l8ffN+R0aJfO46dNhaoldQpdryRKnNvjAPhntfq+/QOhYmJ5nDZdLDYBlW2R43WcRPqKWpNIzayLqAjKlpynsYYTbHYFPWAdgyZxYvg50chv0V3JXd4A86ShPsL2bMDAOyYo4kMflau5IhHUwzFXaonwKBgDxmjZrch/xNvfSGcidKXNg5OdFGwoBbhG5cI+MeQjJaRuUYx+QbxZc1wtrFH9neODwquITI0pnKJZfFIdttMsnJOGCEoSuRWynzPE0yaKhwTXCzYuhbiWwsrQ1lixDm0waeGprcQ1eCnqo7CxeQZvRJGQjbPn8SHeak6tEGgw6hAoGAVIxyQ9NiVNiSoiuPtcplvpdCvAbp5UecbBVBIjDFeFWPkFuHssfLuM2ug/WnpXxNvvShJ2NX61jkK63Vj7by+0w1DFhcr6a8We8q6DsfUQ73bdYZIv1Uojtd30kPaT8185fHQw6RNxNjjFunDKeq6IN3ISfPV7VnXWFpzSQKwBMCgYAN0PhBXUv/mxN/HzZMrY2ja3e+VOgoeDGS0rEJ0JuZG8BLve/5qv+ZudIDGn1VzNkCgMGhxa7h7gyfW9r1I3QmhmAU1lA5vZ62YHJ1aw2naYc+5v0MqW3SBMC382DSP9bT55D1czLjqssX3KIrhy9qIxRzY5k8N/y4K6+pTlifcg==


applepay:
    lineurl: https://buy.itunes.apple.com/verifyReceipt
    boxurl: https://sandbox.itunes.apple.com/verifyReceipt


logging:
    file:
        name: yinpai.log
    pattern:
        console: '%clr(%d{yyyy-MM-dd} [%thread] %-5level %logger{50} - %msg%n)'
        file: '%d{yyyy-MM-dd HH:mm:ss.SSS}  [%thread]  %-5level  %logger{50}  %msg%n'
    path: logs/yinpai
#    打印sql 日志
#    level:
#        org.springframework.security:
#            - debug
#            - info
#        org.springframework.web: debug
#        org.hibernate.SQL: debug
#        org.hibernate.engine.QueryParameters: debug
#        org.hibernate.engine.query.HQLQueryPlan: debug
#        org.hibernate.type.descriptor.sql.BasicBinder: trace

userinfo:
    logo: 'http://yinpai.oss-cn-beijing.aliyuncs.com/yinpai/2020-12-29/fb72c656-a668-4fd6-969b-f7cc06c5b1d0534640.png'


sensitive_url_dev: '/Users/liuzhenda/Downloads/yinpai/server/src/main/resources/sensi_words.txt'

sensitive_url: ''